print(f"Welcome to Emma's calculator")
print(f'Try addition')
value = input('Enter your number: ')
value2 = input('Enter your second number: ')
value3 = int(value) + int(value2)
print(f' your answer is {value3}')
print(f'Try divsion')
value4 = input('Enter your number: ')
value5 = input('Enter your second number: ')
value6 = int(value4)/int(value5)
print(f'your answer is {int(value6)}')
print(f'Try multiplication')
value7 = input('Enter your number: ')
value8 = input('Enter your second number: ')
value9 = int(value7)*int(value8)
print(f'your answer is {value9}')
print(f'Try again!!')


